<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="1" passed="0" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2023-10-09T17:14:21 IST" name="Default suite" finished-at="2023-10-09T17:14:26 IST" duration-ms="4649">
    <groups>
    </groups>
    <test started-at="2023-10-09T17:14:21 IST" name="Default test" finished-at="2023-10-09T17:14:26 IST" duration-ms="4649">
      <class name="vTiger_Organisation_TestScripts.CreateMultipleOrganizationsTest">
        <test-method is-config="true" signature="bsConfiguration()[pri:0, instance:vTiger_Organisation_TestScripts.CreateMultipleOrganizationsTest@68c9133c]" started-at="2023-10-09T17:14:21 IST" name="bsConfiguration" finished-at="2023-10-09T17:14:21 IST" duration-ms="8" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- bsConfiguration -->
        <test-method is-config="true" signature="bcConfiguration()[pri:0, instance:vTiger_Organisation_TestScripts.CreateMultipleOrganizationsTest@68c9133c]" started-at="2023-10-09T17:14:21 IST" name="bcConfiguration" finished-at="2023-10-09T17:14:24 IST" duration-ms="3366" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- bcConfiguration -->
        <test-method signature="createMultipleorgTest(java.lang.String,java.lang.String,java.lang.String,int)[pri:0, instance:vTiger_Organisation_TestScripts.CreateMultipleOrganizationsTest@68c9133c]" started-at="2023-10-09T17:14:24 IST" name="createMultipleorgTest" data-provider="orgNames" finished-at="2023-10-09T17:14:25 IST" duration-ms="500" status="FAIL">
          <exception class="org.testng.internal.reflect.MethodMatcherException">
            <message>
              <![CDATA[
[public void vTiger_Organisation_TestScripts.CreateMultipleOrganizationsTest.createMultipleorgTest(java.lang.String,java.lang.String,java.lang.String,int) throws java.lang.Exception] has no parameters defined but was found to be using a data provider (either explicitly specified or inherited from class level annotation).
Data provider mismatch
Method: createMultipleorgTest([java.lang.String arg0, java.lang.String arg1, java.lang.String arg2, int arg3])
Arguments: [(java.lang.String) wipro,(java.lang.String) Banking,(java.lang.String) Reddy,(java.lang.Double) 85.0]]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.testng.internal.reflect.MethodMatcherException: 
[public void vTiger_Organisation_TestScripts.CreateMultipleOrganizationsTest.createMultipleorgTest(java.lang.String,java.lang.String,java.lang.String,int) throws java.lang.Exception] has no parameters defined but was found to be using a data provider (either explicitly specified or inherited from class level annotation).
Data provider mismatch
Method: createMultipleorgTest([java.lang.String arg0, java.lang.String arg1, java.lang.String arg2, int arg3])
Arguments: [(java.lang.String) wipro,(java.lang.String) Banking,(java.lang.String) Reddy,(java.lang.Double) 85.0]
at org.testng.internal.reflect.DataProviderMethodMatcher.getConformingArguments(DataProviderMethodMatcher.java:46)
at org.testng.internal.Parameters.injectParameters(Parameters.java:909)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:37)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:969)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:829)
at org.testng.TestRunner.run(TestRunner.java:602)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:437)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:431)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:391)
at org.testng.SuiteRunner.run(SuiteRunner.java:330)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1176)
at org.testng.TestNG.runSuites(TestNG.java:1099)
at org.testng.TestNG.run(TestNG.java:1067)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- org.testng.internal.reflect.MethodMatcherException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- createMultipleorgTest -->
        <test-method is-config="true" signature="acConfiguration()[pri:0, instance:vTiger_Organisation_TestScripts.CreateMultipleOrganizationsTest@68c9133c]" started-at="2023-10-09T17:14:25 IST" name="acConfiguration" finished-at="2023-10-09T17:14:26 IST" duration-ms="760" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- acConfiguration -->
        <test-method is-config="true" signature="asConfiguration()[pri:0, instance:vTiger_Organisation_TestScripts.CreateMultipleOrganizationsTest@68c9133c]" started-at="2023-10-09T17:14:26 IST" name="asConfiguration" finished-at="2023-10-09T17:14:26 IST" duration-ms="0" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- asConfiguration -->
      </class> <!-- vTiger_Organisation_TestScripts.CreateMultipleOrganizationsTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
